### ISSUE TITLE
Too many killed photons

### ISSUE THREAD

**Issue by danielseifried** [polaris-MCRT/POLARIS#11]
Hello, I recently switched from Polaris Version 4.0.4 to 4.0.6. I am using an OctTree grid which I created from FLASH input data (but also a self-written test cube with the same result). With 4.0.4 the TEMP and RAT calculations work fine, but with 4.0.6 I get permanently the message "ERROR: Wrong cell border!" using the standard ISRF source. In the end about 80% of all the photons are "killed". This reduces to about 50% when I decrease the starting radius from "2" to "1". In contrast, with Version 4.0.4 the number of killed photons was marginal.
The read-in of the OctTree seems to work fine, all the data (length, mass, density etc) it reports in the POLARIS output are correct. 
Do you have any idea what to look for or to check, as this seems to be relatively deeply embedded in the code? If needed I could provide a small example. Thanks.

**Comment by polaris-MCRT** [comment]
Hey,
it seems like that the calculations of the cell boundaries is not working properly when using the octree grid.
Please try to increase `MIN_LEN_STEP` in `src/Typedefs.h` to, e.g., `1e5` or `1e6`.
If that does not solve the problem, could you please send us your _polaris command file_ and the corresponding _grid file_ for further investigation? ([polaris@astrophysik.uni-kiel.de](mailto:polaris@astrophysik.uni-kiel.de))
Thanks.

**Comment by polaris-MCRT** [comment]
Since POLARIS version 4.05, the counter of killed photon packets is incremented even if the photons emitted by the ISRF do not hit the grid.
(see commit: 100d45d3bc0bc68247f86b0745d0912d58db72b9)

In addition, an error message was added in version 4.06.
(see commit: b271e4eb3d532a18d689222904ffb8e7226bc19c)

**Comment by ZipengHu** [comment]
Hi Polaris team, I faced the same problem when performing CMD_TEMP_RAT on an octree grid. I set an ISRF and a star in the center, 85% photons got killed. The same grid is OK for CMD_DUST_EMISSION. I changed MIN_LEN_STEP to 1e5 and 1e6, no big difference. Could you please tell me any new solution?
