### ISSUE TITLE
Position of stars in output

### ISSUE THREAD

**Issue by danielseifried** [polaris-MCRT/POLARIS#12]
Dear developers,
would it be possible to include the position of stars/point sources used for the TEMP/RAT calculation in the screen output of POLARIS for later cross-checking? If I am not mistaken, so far it is only contained in the command file and if that file is changed at a later point, this information is lost.
Best,
Daniel Seifried

**Comment by polaris-MCRT** [comment]
We added the properties of radiation sources to the screen output.
(see commit 7961c60)
