### ISSUE TITLE
Polaris hangs at TEMP calculation

### ISSUE THREAD

**Issue by danielseifried** [polaris-MCRT/POLARIS#6]
Hi all,
recently me and independently also Michael Küffmeier encountered a problem with the latest Polaris version when trying to calculate the dust temperature. It seems to hang at the line
return phIDs[0]; 
in the routine getPhaseFunctionID  in Parameters.h .

Michael gets the error shown in the image below (which I think is identical):

To my understanding this comes from the fact that phIDs is not an array but a scalar. We both downloaded the clean version and just tried to ran a simple TEMP calculation

![image](https://user-images.githubusercontent.com/79899690/174981686-6def3240-0fdf-493f-ad24-5da56aaa7b1d.png)
.

**Comment by polaris-MCRT** [comment]
Hey,
it seems that `phIDs` was (incorrectly) empty, so `return phIDs[0]` caused a _Segmentation fault_.
This occurred if, for example, no phase function was defined in the command file.
This should be fixed now in the latest version: If no phase function is defined, the default scattering method is _isotropic scattering_.
